### ISSUE TITLE
tab completion of maybe objects hangs with IPython

### ISSUE THREAD

**Issue by alecklandgraf** [ekampf/pymaybe#3]
Hitting `<tab> <tab>` on a `maybe` object seems to hang. Here's my env.

OSX
python 2.7.3
ipython 0.13.1

```pycon
ERROR: Internal Python error in the inspect module.
Below is the traceback from this internal error.
Traceback (most recent call last):
  File "/opt/boxen/data/virturalenvs/seed/lib/python2.7/site-packages/IPython/core/ultratb.py", line 756, in structured_traceback
    records = _fixed_getinnerframes(etb, context, tb_offset)
  File "/opt/boxen/data/virturalenvs/seed/lib/python2.7/site-packages/IPython/core/ultratb.py", line 242, in _fixed_getinnerframes
    records  = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/inspect.py", line 1043, in getinnerframes
    framelist.append((tb.tb_frame,) + getframeinfo(tb, context))
  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/inspect.py", line 1007, in getframeinfo
    lines, lnum = findsource(frame)
  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/inspect.py", line 532, in findsource
    module = getmodule(object, file)
  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/inspect.py", line 500, in getmodule
    os.path.realpath(f)] = module.__name__
  File "/opt/boxen/data/virturalenvs/seed/bin/../lib/python2.7/posixpath.py", line 366, in realpath
    if islink(component):
  File "/opt/boxen/data/virturalenvs/seed/bin/../lib/python2.7/posixpath.py", line 133, in islink
    st = os.lstat(path)
KeyboardInterrupt

Unfortunately, your original traceback can not be constructed.
```

**Comment by ekampf** [comment]
Happens to me to.
I've tried Googling for this problem and noticed completion hanging isn't uncommon...
Any idea how to debug this?

**Comment by alecklandgraf** [comment]
I upgraded ipython to the latest and that didn't help, upgrading python on the mac is a chore, so I'm holding off. 

I haven't tried python 3, so it might be fixed there.

**Comment by ekampf** [comment]
Actually, with Python3 its not hanging:

<img width="1126" alt="screen shot 2015-08-06 at 5 21 43 pm" src="https://cloud.githubusercontent.com/assets/205185/9126222/ac9b82a8-3c5f-11e5-8e5d-8b7c42ad5b5e.png">

**Comment by ekampf** [comment]
@alecklandgraf I just tried again with python 2.7.11 and ipython 4.0.1 and it seems to work now...
